### ISSUE TITLE
Create App Mock Ups

### ISSUE THREAD

**Issue by strossouw** [oceanlatte/sinato#8]
First Draft of Dashboard

![image](https://user-images.githubusercontent.com/105831699/187808832-403c7dbb-bd41-434f-be29-2c7364a9d64a.png)

**Comment by strossouw** [comment]
Second draft with box outlines and added notes
![image](https://user-images.githubusercontent.com/105831699/187809831-f10d35ae-8576-43ba-80bb-4920e0ed7eaa.png)

**Comment by oceanlatte** [comment]
![image](https://user-images.githubusercontent.com/103909097/188256452-a6d668ae-02d9-4a2b-a2dd-dbd87ddb328b.png)

**Comment by oceanlatte** [comment]
![image](https://user-images.githubusercontent.com/103909097/188283534-592677d8-7d56-4644-a330-829a304a361b.png)
updated with comment examples and emoji reactions example
